stages:
  - deploy

pages:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install make librsvg2-bin --no-install-recommends -y
    - python -m pip install sphinx furo sphinxcontrib.asciinema sphinxemoji sphinxcontrib-svg2pdfconverter
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
